/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as TasbihRouteImport } from './routes/tasbih'
import { Route as SelectMasjidRouteImport } from './routes/select-masjid'
import { Route as QuranRouteImport } from './routes/quran'
import { Route as QiblaRouteImport } from './routes/qibla'
import { Route as PrayerSettingsRouteImport } from './routes/prayer-settings'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MuazzinRouteImport } from './routes/muazzin'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MasjidsRouteImport } from './routes/masjids'
import { Route as HijriRouteImport } from './routes/hijri'
import { Route as DuasRouteImport } from './routes/duas'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuranSurahNumberRouteImport } from './routes/quran_.$surahNumber'
import { Route as DuasCategoryRouteImport } from './routes/duas_.$category'

const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const TasbihRoute = TasbihRouteImport.update({
  id: '/tasbih',
  path: '/tasbih',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectMasjidRoute = SelectMasjidRouteImport.update({
  id: '/select-masjid',
  path: '/select-masjid',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranRoute = QuranRouteImport.update({
  id: '/quran',
  path: '/quran',
  getParentRoute: () => rootRouteImport,
} as any)
const QiblaRoute = QiblaRouteImport.update({
  id: '/qibla',
  path: '/qibla',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerSettingsRoute = PrayerSettingsRouteImport.update({
  id: '/prayer-settings',
  path: '/prayer-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MuazzinRoute = MuazzinRouteImport.update({
  id: '/muazzin',
  path: '/muazzin',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MasjidsRoute = MasjidsRouteImport.update({
  id: '/masjids',
  path: '/masjids',
  getParentRoute: () => rootRouteImport,
} as any)
const HijriRoute = HijriRouteImport.update({
  id: '/hijri',
  path: '/hijri',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasRoute = DuasRouteImport.update({
  id: '/duas',
  path: '/duas',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuranSurahNumberRoute = QuranSurahNumberRouteImport.update({
  id: '/quran_/$surahNumber',
  path: '/quran/$surahNumber',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasCategoryRoute = DuasCategoryRouteImport.update({
  id: '/duas_/$category',
  path: '/duas/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/duas': typeof DuasRoute
  '/hijri': typeof HijriRoute
  '/masjids': typeof MasjidsRoute
  '/more': typeof MoreRoute
  '/muazzin': typeof MuazzinRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer': typeof PrayerRoute
  '/prayer-settings': typeof PrayerSettingsRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/select-masjid': typeof SelectMasjidRoute
  '/tasbih': typeof TasbihRoute
  '/zakat': typeof ZakatRoute
  '/duas/$category': typeof DuasCategoryRoute
  '/quran/$surahNumber': typeof QuranSurahNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/duas': typeof DuasRoute
  '/hijri': typeof HijriRoute
  '/masjids': typeof MasjidsRoute
  '/more': typeof MoreRoute
  '/muazzin': typeof MuazzinRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer': typeof PrayerRoute
  '/prayer-settings': typeof PrayerSettingsRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/select-masjid': typeof SelectMasjidRoute
  '/tasbih': typeof TasbihRoute
  '/zakat': typeof ZakatRoute
  '/duas/$category': typeof DuasCategoryRoute
  '/quran/$surahNumber': typeof QuranSurahNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/donate': typeof DonateRoute
  '/duas': typeof DuasRoute
  '/hijri': typeof HijriRoute
  '/masjids': typeof MasjidsRoute
  '/more': typeof MoreRoute
  '/muazzin': typeof MuazzinRoute
  '/onboarding': typeof OnboardingRoute
  '/prayer': typeof PrayerRoute
  '/prayer-settings': typeof PrayerSettingsRoute
  '/qibla': typeof QiblaRoute
  '/quran': typeof QuranRoute
  '/select-masjid': typeof SelectMasjidRoute
  '/tasbih': typeof TasbihRoute
  '/zakat': typeof ZakatRoute
  '/duas_/$category': typeof DuasCategoryRoute
  '/quran_/$surahNumber': typeof QuranSurahNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/donate'
    | '/duas'
    | '/hijri'
    | '/masjids'
    | '/more'
    | '/muazzin'
    | '/onboarding'
    | '/prayer'
    | '/prayer-settings'
    | '/qibla'
    | '/quran'
    | '/select-masjid'
    | '/tasbih'
    | '/zakat'
    | '/duas/$category'
    | '/quran/$surahNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donate'
    | '/duas'
    | '/hijri'
    | '/masjids'
    | '/more'
    | '/muazzin'
    | '/onboarding'
    | '/prayer'
    | '/prayer-settings'
    | '/qibla'
    | '/quran'
    | '/select-masjid'
    | '/tasbih'
    | '/zakat'
    | '/duas/$category'
    | '/quran/$surahNumber'
  id:
    | '__root__'
    | '/'
    | '/donate'
    | '/duas'
    | '/hijri'
    | '/masjids'
    | '/more'
    | '/muazzin'
    | '/onboarding'
    | '/prayer'
    | '/prayer-settings'
    | '/qibla'
    | '/quran'
    | '/select-masjid'
    | '/tasbih'
    | '/zakat'
    | '/duas_/$category'
    | '/quran_/$surahNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DonateRoute: typeof DonateRoute
  DuasRoute: typeof DuasRoute
  HijriRoute: typeof HijriRoute
  MasjidsRoute: typeof MasjidsRoute
  MoreRoute: typeof MoreRoute
  MuazzinRoute: typeof MuazzinRoute
  OnboardingRoute: typeof OnboardingRoute
  PrayerRoute: typeof PrayerRoute
  PrayerSettingsRoute: typeof PrayerSettingsRoute
  QiblaRoute: typeof QiblaRoute
  QuranRoute: typeof QuranRoute
  SelectMasjidRoute: typeof SelectMasjidRoute
  TasbihRoute: typeof TasbihRoute
  ZakatRoute: typeof ZakatRoute
  DuasCategoryRoute: typeof DuasCategoryRoute
  QuranSurahNumberRoute: typeof QuranSurahNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasbih': {
      id: '/tasbih'
      path: '/tasbih'
      fullPath: '/tasbih'
      preLoaderRoute: typeof TasbihRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-masjid': {
      id: '/select-masjid'
      path: '/select-masjid'
      fullPath: '/select-masjid'
      preLoaderRoute: typeof SelectMasjidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran': {
      id: '/quran'
      path: '/quran'
      fullPath: '/quran'
      preLoaderRoute: typeof QuranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qibla': {
      id: '/qibla'
      path: '/qibla'
      fullPath: '/qibla'
      preLoaderRoute: typeof QiblaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer-settings': {
      id: '/prayer-settings'
      path: '/prayer-settings'
      fullPath: '/prayer-settings'
      preLoaderRoute: typeof PrayerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/muazzin': {
      id: '/muazzin'
      path: '/muazzin'
      fullPath: '/muazzin'
      preLoaderRoute: typeof MuazzinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masjids': {
      id: '/masjids'
      path: '/masjids'
      fullPath: '/masjids'
      preLoaderRoute: typeof MasjidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hijri': {
      id: '/hijri'
      path: '/hijri'
      fullPath: '/hijri'
      preLoaderRoute: typeof HijriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas': {
      id: '/duas'
      path: '/duas'
      fullPath: '/duas'
      preLoaderRoute: typeof DuasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quran_/$surahNumber': {
      id: '/quran_/$surahNumber'
      path: '/quran/$surahNumber'
      fullPath: '/quran/$surahNumber'
      preLoaderRoute: typeof QuranSurahNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas_/$category': {
      id: '/duas_/$category'
      path: '/duas/$category'
      fullPath: '/duas/$category'
      preLoaderRoute: typeof DuasCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DonateRoute: DonateRoute,
  DuasRoute: DuasRoute,
  HijriRoute: HijriRoute,
  MasjidsRoute: MasjidsRoute,
  MoreRoute: MoreRoute,
  MuazzinRoute: MuazzinRoute,
  OnboardingRoute: OnboardingRoute,
  PrayerRoute: PrayerRoute,
  PrayerSettingsRoute: PrayerSettingsRoute,
  QiblaRoute: QiblaRoute,
  QuranRoute: QuranRoute,
  SelectMasjidRoute: SelectMasjidRoute,
  TasbihRoute: TasbihRoute,
  ZakatRoute: ZakatRoute,
  DuasCategoryRoute: DuasCategoryRoute,
  QuranSurahNumberRoute: QuranSurahNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
